# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ju8-jIVticQLxoOYFPuc0TbT9FrQP0ix

**Job Market Analysis**

Objective :
Analyze skill demand and salary patterns across major data roles
to identify high-demand and high-paying skills.
"""

import ast
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df.head()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else x
)

df_US = df[df['job_country'] == 'United States'].copy()
df_US.shape

top_roles = df_US['job_title_short'].value_counts().head(3)
top_roles

df_top_roles = df_US[df_US['job_title_short'].isin(top_roles.index)]
df_top_roles.shape

df_skills = df_top_roles.explode('job_skills')
df_skills = df_skills.dropna(subset=['job_skills'])
df_skills.head()

df_skill_count = (
    df_skills
    .groupby(['job_title_short', 'job_skills'])
    .size()
    .reset_index(name='skill_count')
    .sort_values(by='skill_count', ascending=False)
)

df_skill_count.head(10)

df_role_totals = (
    df_top_roles['job_title_short']
    .value_counts()
    .reset_index()
)

df_role_totals.columns = ['job_title_short', 'total_jobs']

df_skill_percent = df_skill_count.merge(df_role_totals, on='job_title_short')

df_skill_percent['skill_percent'] = (
    df_skill_percent['skill_count'] / df_skill_percent['total_jobs']
) * 100

df_skill_percent.head()

sns.set_theme(style='ticks')

fig, ax = plt.subplots(len(top_roles), 1, figsize=(8, 10))

for i, role in enumerate(top_roles.index):
    df_plot = (
        df_skill_percent[df_skill_percent['job_title_short'] == role]
        .sort_values(by='skill_percent', ascending=False)
        .head(5)
    )

    sns.barplot(
        data=df_plot,
        x='skill_percent',
        y='job_skills',
        ax=ax[i]
    )

    ax[i].set_title(role)
    ax[i].set_xlabel('Percentage of Job Postings')
    ax[i].set_ylabel('')

plt.tight_layout()
plt.show()

"""Skill Demand (US Market)

Top 3 Roles:

Data Analyst

Data Scientist

Data Engineer

Key Findings

SQL is required across all three roles.

Python dominates Data Scientist and Data Engineer roles.

Excel & Tableau are more concentrated in Data Analyst positions.

Cloud skills (AWS, Azure, Spark) are mainly required for Data Engineers.

Conclusion:
SQL is the foundational skill. Python is essential for advanced roles. Cloud tools differentiate Data Engineers from other data roles.

Skill Trend Analysis                                                                        
Focus: Data Analyst – United States                                                 
We analyze how in-demand skills for Data Analysts change over time.
The goal is to understand whether certain skills are increasing, stable, or declining in demand.
"""

df_DA_US = df[
    (df['job_title_short'] == 'Data Analyst') &
    (df['job_country'] == 'United States')
].copy()

df_DA_US['job_posted_month_no'] = df_DA_US['job_posted_date'].dt.month

df_DA_US_explode = df_DA_US.explode('job_skills')

df_DA_US_pivot = df_DA_US_explode.pivot_table(
    index='job_posted_month_no',
    columns='job_skills',
    aggfunc='size',
    fill_value=0
)

df_DA_US_pivot.loc['Total'] = df_DA_US_pivot.sum()

df_DA_US_pivot = df_DA_US_pivot[
    df_DA_US_pivot.loc['Total'].sort_values(ascending=False).index
]

df_DA_US_pivot = df_DA_US_pivot.drop('Total')

df_DA_US_pivot.iloc[:, :5].plot(kind='line')

plt.title('Trending Top Skills for Data Analysts in the US')
plt.ylabel('Count')
plt.xlabel('')
plt.show()

DA_totals = df_DA_US.groupby('job_posted_month_no').size()
df_DA_US_percent = df_DA_US_pivot.div(DA_totals, axis=0) * 100

df_DA_US_percent.iloc[:, :5].plot(kind='line')

plt.title('Trending Top Skills for Data Analysts in the US')
plt.ylabel('Percentage of Job Postings')
plt.xlabel('')
plt.show()

"""SQL remains consistently the most required skill across all months.

Excel maintains strong demand but shows slight decline toward the end of the year.

Python and Tableau remain stable with moderate fluctuations.

Overall, skill demand for Data Analysts is relatively stable throughout the year.

Salary Analysis                                                                              
Focus: United States Market                                                                                                                                                                                                                                                  In this section, we analyze salary distributions across major data roles
and identify which skills are associated with higher median salaries.
"""

df_US_salary = df[
    (df['job_country'] == 'United States') &
    (df['salary_year_avg'].notna())
].copy()

top_roles_salary = df_US_salary['job_title_short'].value_counts().index[:6].tolist()

df_US_top6 = df_US_salary[
    df_US_salary['job_title_short'].isin(top_roles_salary)
]

top_roles_salary = df_US_salary['job_title_short'].value_counts().index[:6].tolist()

df_US_top6 = df_US_salary[
    df_US_salary['job_title_short'].isin(top_roles_salary)
]

job_order = top_roles_salary
sns.boxplot(
    data=df_US_top6,
    x='salary_year_avg',
    y='job_title_short',
    order=job_order
)

plt.title('Salary Distribution of Top Data Roles (US)')
plt.xlabel('Yearly Salary (USD)')
plt.ylabel('')
plt.xlim(0, 600000)

plt.gca().xaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${int(x/1000)}K')
)

plt.show()

"""Senior Data Scientist and Senior Data Engineer roles have the highest median salaries.

Data Scientist and Data Engineer roles earn significantly more than Data Analyst roles.

Salary distributions show wide variability, especially for Data Scientist positions.

"""

df_DA_US = df[
    (df['job_title_short'] == 'Data Analyst') &
    (df['job_country'] == 'United States') &
    (df['salary_year_avg'].notna())
].copy()

df_DA_US = df_DA_US.explode('job_skills')
df_DA_skills = (
    df_DA_US
    .groupby('job_skills')['salary_year_avg']
    .agg(['count', 'median'])
    .sort_values(by='count', ascending=False)
)

df_DA_top_demand = df_DA_skills.head(10).sort_values(by='median', ascending=False)
df_DA_top_demand
df_DA_skills_filtered = df_DA_skills[df_DA_skills['count'] > 50]

df_DA_top_pay = (
    df_DA_skills_filtered
    .sort_values(by='median', ascending=False)
    .head(10)
)

df_DA_top_pay

"""Higher-paying Data Analyst roles are associated with big data and cloud technologies such as Hadoop, Snowflake, Databricks, and Spark.

Cloud platforms like AWS and Azure also show strong salary impact.

Advanced technical skills significantly increase earning potential compared to traditional analyst tools.

"""

DA_job_count = len(df_DA_US)

df_DA_skills['skill_percent'] = (
    df_DA_skills['count'] / DA_job_count * 100
)
skill_limit = 5

df_DA_skills_high_demand = df_DA_skills[
    df_DA_skills['skill_percent'] > skill_limit
]

plt.scatter(
    df_DA_skills_high_demand['skill_percent'],
    df_DA_skills_high_demand['median']
)

plt.xlabel('Percent of Data Analyst Jobs')
plt.ylabel('Median Salary (USD)')
plt.title('Optimal Skills for Data Analysts (US)')

plt.gca().yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f'${int(x/1000)}K')
)

plt.show()

"""Python provides the best balance between demand and salary for Data Analysts.

SQL has the highest demand but slightly lower median salary.

Advanced analytical and programming skills lead to stronger earning potential compared to traditional tools like Excel.

"""