# -*- coding: utf-8 -*-
"""Data Cleaning and EDA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H46tUARhm3k2InT30LYcfrDSCOx8aAKh

Project Goal :
This notebook explores the structure of the job market dataset
to understand the distribution of roles, companies, locations,
and job benefits in the data industry.

Questions to Explore :
  What are the most common data  roles?                                                      
  Which countries post the most data jobs?                                                
  Which companies are hiring the most?                                                   
  What benefits are commonly offered?
"""

import ast
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df.head()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else x
)

df.info()

df_plot = df['job_title_short'].value_counts().to_frame().reset_index()
df_plot.columns = ['job_title_short', 'count']

sns.set_theme(style='ticks')
sns.barplot(data=df_plot, x='count', y='job_title_short', palette='dark:b_r')

sns.despine()
plt.title('Number of Jobs per Job Title')
plt.xlabel('Number of Jobs')
plt.ylabel('')
plt.show()

df_plot = df['job_country'].value_counts().head(20).to_frame().reset_index()
df_plot.columns = ['job_country', 'count']

sns.barplot(data=df_plot, x='count', y='job_country', palette='dark:b_r')

sns.despine()
plt.title('Number of Jobs per Country')
plt.xlabel('Number of Jobs')
plt.ylabel('')
plt.show()

df_plot = df['company_name'].value_counts().head(20).to_frame().reset_index()
df_plot.columns = ['company_name', 'count']

sns.barplot(
    data=df_plot,
    x='count',
    y='company_name',
    hue='company_name',
    palette='dark:b_r',
    legend=False
)

sns.despine()
plt.title('Number of Jobs per Company')
plt.xlabel('Number of Jobs')
plt.ylabel('')
plt.show()

dict_column = {
    'job_work_from_home': 'Work from Home Offered',
    'job_no_degree_mention': 'No Degree Mentioned',
    'job_health_insurance': 'Health Insurance Offered'
}

fig, ax = plt.subplots(1, 3, figsize=(12, 4))

for i, (column, title) in enumerate(dict_column.items()):
    ax[i].pie(
        df[column].value_counts(),
        labels=['False', 'True'],
        autopct='%1.1f%%',
        startangle=90
    )
    ax[i].set_title(title)

plt.show()

df_DA_US = df[
    (df['job_country'] == 'United States') &
    (df['job_title_short'] == 'Data Analyst')
]

df_DA_US.shape

df_plot = (
    df_DA_US['job_location']
    .value_counts()
    .head(10)
    .to_frame()
    .reset_index()
)

df_plot.columns = ['job_location', 'count']

sns.barplot(
    data=df_plot,
    x='count',
    y='job_location',
    hue='job_location',
    palette='dark:b_r',
    legend=False
)

sns.despine()
plt.title('Top 10 Locations for Data Analyst in the US')
plt.xlabel('Number of Jobs')
plt.ylabel('')
plt.show()

dict_column = {
    'job_work_from_home': 'Work from Home Offered',
    'job_no_degree_mention': 'No Degree Mentioned',
    'job_health_insurance': 'Health Insurance Offered'
}

fig, ax = plt.subplots(1, 3, figsize=(12, 4))

for i, (column, title) in enumerate(dict_column.items()):
    ax[i].pie(
        df_DA_US[column].value_counts(),
        labels=['False', 'True'],
        autopct='%1.1f%%',
        startangle=90
    )
    ax[i].set_title(title)

plt.show()

df_plot = (
    df_DA_US['company_name']
    .value_counts()
    .head(10)
    .to_frame()
    .reset_index()
)

df_plot.columns = ['company_name', 'count']

sns.barplot(
    data=df_plot,
    x='count',
    y='company_name',
    hue='company_name',
    palette='dark:b_r',
    legend=False
)

sns.despine()
plt.title('Top 10 Companies Hiring Data Analysts (US)')
plt.xlabel('Number of Jobs')
plt.ylabel('')
plt.show()