# -*- coding: utf-8 -*-
"""Insights and Recommendations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRmKYKmtpWA3-ELUiHCB1py-dRqZ1ZG4

Final Insights and Recommendations                                                       
US Data Job Market Analysis

## Key Insights

1. SQL is the foundational skill across all major data roles.
2. Python dominates Data Scientist roles and provides strong salary growth for Data Analysts.
3. Cloud and Big Data technologies (AWS, Azure, Spark, Snowflake) significantly increase salary potential.
4. Data Analyst roles have lower median salaries compared to Data Scientist and Data Engineer roles.
5. Skill demand remains relatively stable throughout the year.

## Final Recommendation

To maximize career growth in the US data market:

1. Start with SQL and Excel.
2. Add Python for advanced analytics.
3. Learn a visualization tool.
4. Develop cloud or big data skills to significantly increase salary potential.

##  Highlights

- Analyzed 785K+ US job postings using Python and Pandas.
- Identified top demanded skills across Data Analyst, Data Scientist, and Data Engineer roles.
- Evaluated salary distributions and skill-based earning potential.
- Built demand vs salary optimization model for Data Analysts.
- Derived actionable recommendations for skill development strategy.
"""